using MyLittleWarbandEx.PatchTools;
using System;
using HarmonyLib;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TaleWorlds.CampaignSystem;
using TaleWorlds.Core;
using TaleWorlds.CampaignSystem.CampaignBehaviors;
using TaleWorlds.CampaignSystem.GameComponents;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.CampaignSystem.ViewModelCollection.KingdomManagement;
using System.Runtime.CompilerServices;
using SandBox.GauntletUI.AutoGenerated0;

namespace MyLittleWarbandEx.Patches
{
    internal sealed class CharacterObjectPatch : PatchClass<CharacterObjectPatch>
     {

         public static CultureObject ?Culture;
         protected override IEnumerable<Patch> Prepare()
         {
             //HarmonyLib.BUTR.Extensions.AccessTools2.DeclaredProperty(typeof(CultureObject), "Culture");
             return new Patch[]
             {
                 //new Prefix("IsMounted","IsMounted")
             };
         }

         public static void IsMounted(ref CharacterObject __instance)
         {
            
         }

     }
}
