using MyLittleWarbandEx.CampaignBehaviors;
using MyLittleWarbandEx.ViewModel;
using SandBox.GauntletUI.AutoGenerated1;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.Extensions;
using TaleWorlds.Core;
using TaleWorlds.Core.ViewModelCollection.ImageIdentifiers;
using TaleWorlds.Library;
using TaleWorlds.LinQuick;
using TaleWorlds.MountAndBlade.View;
using TaleWorlds.ObjectSystem;
using static System.Net.Mime.MediaTypeNames;
using static TaleWorlds.CampaignSystem.CampaignBehaviors.LordConversationsCampaignBehavior;
using static TaleWorlds.Core.Equipment;

namespace MyLittleWarbandEx.ViewModel;

public class EquipmentSelectorVM : FilterableViewModel
{

    //public MBBindingList<EquipmentCardVM> Cards;

    public MBBindingList<EquipmentCardRowVM> Rows { get; set; }

    private int _sortIndex = 0;

    private bool _isArmor;
    
    private List<string> _sortOptions = new List<string>()
    {
        "Default",
        "Name",
        "Weight",
        "Tier"
    };

    private CharacterObject _troop;
    private string _equipmentType;
    private bool _ascending = true;
    private string _ascendingTxt = "Ascending";
    private string _sortByText = "Default";
    private bool _showEmpty = false;
    private string _showEmptyText = "Show Empty";
    private List<ItemObject> _items;
    private Dictionary<string, List<string>> _filters;
    public List<string> _filter_Culture_String = new List<string>();
    public List<ArmorComponent.ArmorMaterialTypes> _filter_armour_types = new List<ArmorComponent.ArmorMaterialTypes>();


    private string _cultureFilter;
    private string _tierFilter;
    private string _equipmentFilter;

    [DataSourceProperty]
    public string EquipmentFilterButton { 
        get
        {
            return (_equipmentType.StartsWith("Wep") ? "Filter Weapon Type" : "Filter Armor Type");
        }
    }

    [DataSourceProperty]
    public string CultureFilter
    {
        get
        {
            return _cultureFilter;
        }
        set
        {
            if (value != _cultureFilter)
            {
                _cultureFilter = (value);
                base.OnPropertyChangedWithValue<string>(value, "CultureFilter");
            }
        }
    }

    [DataSourceProperty]
    public string TierFilter
    {
        get
        {
            return _tierFilter;
        }
        set
        {
            if (value != _tierFilter)
            {
                _tierFilter = (value);
                base.OnPropertyChangedWithValue<string>(value, "TierFilter");
            }
        }
    }

    [DataSourceProperty]
    public string EquipmentFilter
    {
        get
        {
            return _equipmentFilter;
        }
        set
        {
            if (value != _equipmentFilter)
            {
                _equipmentFilter = (value);
                base.OnPropertyChangedWithValue<string>(value, "EquipmentFilter");
            }
        }
    }


    [DataSourceProperty]
    public string SortByText
    {
        get
        {
            return _sortByText;
        }
        set
        {
            if (value != _sortByText)
            {
                _sortByText = (value);
                base.OnPropertyChangedWithValue<string>(value, "SortByText");
            }
        }
    }

    [DataSourceProperty]
    public string ShowEmptyText
    {
        get
        {
            return (_showEmpty ? "Hide Empty" : "Show Empty"); ;
        }
        set
        {
            if (value != _showEmptyText)
            {
                _showEmptyText = (value);
                _showEmpty = (_showEmptyText == "Hide Empty" ? true : false);
                base.OnPropertyChangedWithValue<string>(value, "ShowEmptyText");
            }
        }
    }

    [DataSourceProperty]
    public bool ShowEmpty
    {
        get
        {
            return _showEmpty;
        }
        set
        {
            _showEmpty = value;
            base.OnPropertyChangedWithValue(value, "ShowEmpty");
        }
    }

    [DataSourceProperty]
    public string AscendingText
    {
        get
        {
            return (_ascending ? "Ascending ↓" : "Descending ↑");
        }
        set
        {
            if (value != _sortByText)
            {
                _ascendingTxt = (value);
                _ascending = (_ascendingTxt == "Ascending" ? true : false);
                base.OnPropertyChangedWithValue<string>(value, "AscendingText");
            }
        }
    }

    

    public EquipmentSelectorVM(List<ItemObject> items, CharacterObject troop, string equipmentType)
    {
        _items = items;
        _troop = troop;
        _equipmentType = equipmentType;

        Rows = new MBBindingList<EquipmentCardRowVM>();
        
        //Different values based on the itemType
        if(_equipmentType.StartsWith("Wep"))
        {
            
            _sortOptions.Add("SwingDamage");
            _sortOptions.Add("ThrustDamage");
            _sortOptions.Add("SwingSpeed");
            _sortOptions.Add("ThrustSpeed");
            _sortOptions.Add("Handling");
            _sortOptions.Add("Accuracy");
            _sortOptions.Add("MissleDamage");
        }
        else if(_equipmentType == "Horse")
        {
            _sortOptions.Add("ChargeDamage");
            _sortOptions.Add("Speed");
            _sortOptions.Add("HitPoints");
            _sortOptions.Add("Maneuver");
        }
        else
        {
            _isArmor = true;
            _sortOptions.Add("BodyArmor");
            _sortOptions.Add("ArmArmor");
            _sortOptions.Add("LegArmor");
            _sortOptions.Add("HeadArmor");
            _sortOptions.Add("MaterialType");
        }

        _filters = new Dictionary<string, List<string>>() { 
        
        };

        
        RefreshDataView();
    }

    public void EquipmentViewSortPopup()
    {
        List<InquiryElement> list = new List<InquiryElement>();
        foreach (string sortItem in _sortOptions)
        {
            list.Add(new InquiryElement(sortItem, sortItem, null));
        }
        string newSortByText = "";
        MBInformationManager.ShowMultiSelectionInquiry(new MultiSelectionInquiryData("Filter by options:", "", list, isExitShown: true, 1, 1, "Continue", null, delegate (List<InquiryElement> args)
        {
            if (args == null || args.Any())
            {
                InformationManager.HideInquiry();
                IEnumerable<string> enumerable = args.Select((InquiryElement element) => element.Identifier as string);

                foreach (string item in enumerable)
                {
                    newSortByText = item;
                    break;
                }
                if (newSortByText != _sortByText)
                {
                    SortByText = newSortByText;
                    this.Rows.Clear();
                    this.RefreshDataView();
                }
            }
        }, null));
         
    }


    private bool isFilterEnabled()
    {
        var flag1 = (base.FilterTiers.Count > 0);
        var flag2 = (base.FilterCulture.Count > 0);
        var flag3 = (base.FilterWeaponTypes.Count > 0);
        var flag4 = (_filter_armour_types.Count > 0);
        bool filterEnabled = (flag1 || flag2 || flag3 || flag4);

        
        
        
        if (filterEnabled)
        {
            CultureFilter = string.Join(",", base.FilterCulture);
            if (_equipmentType.StartsWith("Wep"))
                EquipmentFilter = string.Join(",", base.FilterWeaponTypes);
            else
                EquipmentFilter = string.Join(",", _filter_armour_types);
            TierFilter = string.Join(",", base.FilterTiers);
        }
        return filterEnabled;
    }

    public List<ItemObject> GetSortedList(List<ItemObject> currentList)
    {
        List<ItemObject> localList = currentList;

        Func<ItemObject, object> keySelector;
        Func<ItemObject, bool> filterNull;

        if (!string.IsNullOrEmpty(_sortByText) && _sortByText != "Default")
        {
            filterNull = p =>
            {
                return true;
            };

            keySelector = p =>
            {
                var propInfo = p.GetType().GetProperty(_sortByText).ToString();
                if (propInfo == null) return null; // Handle property not found
                return propInfo;
            };
            if ((_sortByText == "Name"))
            { 
                keySelector = p =>
                {
                    return p.Name.ToString();
                };
            }
            if (_sortByText == "Weight" || _sortByText == "Tier")
            {
                //Different values based on the itemType
                keySelector = p =>
                {
                    var propInfo = p.GetType().GetProperty(_sortByText);
                    if (propInfo == null) return null; // Handle property not found
                    return propInfo.GetValue(p);
                };

                filterNull = p =>
                {
                    var propInfo = p.GetType().GetProperty(_sortByText);
                    return (propInfo.GetValue(p) != null);
                };

            }
            else if (_equipmentType.StartsWith("Wep"))
            {
                

                keySelector = p =>
                {
                    var weapon = p.Weapons.FirstOrDefault(); // Use FirstOrDefault for safety
                    if (weapon == null) return null; // Handle null weapon gracefully

                    var propInfo = weapon.GetType().GetProperty(_sortByText);
                    if (propInfo == null) return null; // Handle property not found
                   


                    return propInfo.GetValue(weapon);
                };

                filterNull = p =>
                {
                    var weapon = p.Weapons.FirstOrDefault(); // Use FirstOrDefault for safety
                    if (weapon == null) return false; // Handle null weapon gracefully

                    var propInfo = weapon.GetType().GetProperty(_sortByText);
                    if (propInfo == null) return false; // Handle property not found
                    
                    var weaponValue = propInfo.GetValue(weapon);
                    if (weaponValue == null)
                        return false;

                    int value;
                    if (!int.TryParse(weaponValue?.ToString(), out value))
                        return false;
                    return (value > 0);
                };
            }
            else if (_equipmentType.StartsWith("Horse"))
            {
                keySelector = p =>
                {
                    var horse = p.HorseComponent; // Use FirstOrDefault for safety
                    if (horse == null) return null; // Handle null weapon gracefully

                    var propInfo = horse.GetType().GetProperty(_sortByText);
                    if (propInfo == null) return null; // Handle property not found

                    return propInfo.GetValue(horse);
                };
                filterNull = p =>
                {
                    var horse = p.HorseComponent; // Use FirstOrDefault for safety
                    if (horse == null) return false; // Handle null weapon gracefully

                    var propInfo = horse.GetType().GetProperty(_sortByText);
                    if (propInfo == null) return false; // Handle property not found

                    return (propInfo.GetValue(horse) != null);
                };
            }
            else if (_isArmor)
            {
                keySelector = p =>
                {
                    var armor = p.ArmorComponent; // Use FirstOrDefault for safety
                    if (armor == null) return null; // Handle null weapon gracefully

                    var propInfo = armor.GetType().GetProperty(_sortByText);
                    if (propInfo == null) return null; // Handle property not found

                    return propInfo.GetValue(armor);
                };

                filterNull = p =>
                {
                    var armor = p.ArmorComponent; // Use FirstOrDefault for safety
                    if (armor == null) return false; // Handle null weapon gracefully

                    var propInfo = armor.GetType().GetProperty(_sortByText);
                    if (propInfo == null) return false; // Handle property not found

                    var armorValue = propInfo.GetValue(armor);
                    if (armorValue == null)
                        return false;

                    int value;
                    if (!int.TryParse(armorValue?.ToString(), out value))
                        return false;
                    else if (!string.IsNullOrEmpty(armorValue?.ToString()))
                    {
                        return true;
                    }

                    return (value > 0);
                };

            }
            // The existing reflection logic for when _sortByText is valid
            if (!_showEmpty)
            {
                localList = localList.Where(filterNull).ToList();
            }

            if (_ascending && (keySelector != null))
            {
                localList = localList.OrderBy(keySelector).ToList();
            }
            else
            {
                localList = localList.OrderByDescending(keySelector).ToList();
            }
        }
        return localList;
    }

    public List<ItemObject> GetFilteredList(List<ItemObject> currentList)
    {

        List<ItemObject> localList = currentList;
        List<ItemObject> filteredList = new List<ItemObject>();
        foreach (ItemObject objectType in localList)
        {
            if (CustomUnitsBehavior.MatchesFilter(objectType, base.FilterTiers, base.FilterCulture, base.FilterWeaponTypes, _filter_armour_types))
            {
                filteredList.Add(objectType);
            }
        }
        return filteredList;
    }
    
    public override void RefreshData()
    {
        this.RefreshDataView();
    }

    public override void RefreshValues()
    {
        base.RefreshValues();
    }

    private void RefreshDataView()
    {
        this.Rows.Clear();
        List<ItemObject> localList = _items;
        if (isFilterEnabled())
        {
            localList = GetFilteredList(localList);
        }
        localList = GetSortedList(localList);

        // Use a local variable to manage the cards for the current row being built
        EquipmentCardRowVM currentRow = new EquipmentCardRowVM();

        // Add initial empty card
        currentRow.AddCard(null, _troop, _equipmentType);

        foreach (ItemObject item in localList)
        {
            currentRow.AddCard(item, _troop, _equipmentType);

            // If we hit 5 items, we finalize the row and start a new list
            if (currentRow.Cards.Count == 5)
            {
                // Add the finalized row to the main Rows list
                Rows.Add(currentRow);

                // Start a new, empty list for the next row
                currentRow = new EquipmentCardRowVM();
            }
        }

        // Add any remaining cards as a final (potentially incomplete) row
        if (currentRow.Cards.Count > 0)
        {
            Rows.Add(currentRow);
        }
        this.RefreshValues();
    }


    public void EquipmentViewFilter()
    {
        this.RefreshValues();
    }



    public void EquipmentViewSort()
    {
        if((_sortIndex + 2) > _sortOptions.Count )
        {
            _sortIndex = 0;
        }
        else
        {
            _sortIndex++;
        }
        SortByText = _sortOptions[ _sortIndex ];
        this.RefreshDataView();
    }

    public void EquipmentViewSortOrder()
    {
        
        AscendingText = _ascending ? "Descending" : "Ascending";
        if (this._sortByText != "Default")
        {
            this.RefreshDataView();
        }
    }
    
    public void FilterCulturesPopup()
    {
        CustomUnitsBehavior.FilterCulturesPopup(this);
    }

    public void FilterCulturesClear()
    {
        base.FilterCulture.Clear();
        this.CultureFilter = "";
        this.RefreshDataView();
    }

    public void FilterTiersPopup()
    {
        CustomUnitsBehavior.FilterTiersPopup(this);
        
    }

    public void FilterTierClear()
    {
        base.FilterTiers.Clear();
        this.TierFilter = "";
        this.RefreshDataView();
    }

    public void FilterEquipmentPopup()
    {
        if (_equipmentType.StartsWith("Wep"))
        {
            CustomUnitsBehavior.FilterWeaponsPopup(this);

        }
        else if (_equipmentType != "Horse")
        {
            CustomUnitsBehavior.FilterArmourPopup(this);
        }
    }

    public void FilterEquipmentClear()
    {
        base.FilterWeaponTypes.Clear();
        this._filter_armour_types.Clear();
        this.EquipmentFilter = "";
        this.RefreshDataView();
    }


    public void ShowEmptyToggle()
    {
        ShowEmptyText = _showEmpty ? "Hide Empty" : "Show Empty";
        this.RefreshDataView();
    }

    public void Close()
    {
        EquipmentSelectorBehavior.DeleteVMLayer();
    }
}