using SandBox.GauntletUI.AutoGenerated0;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TaleWorlds.CampaignSystem.ViewModelCollection.Inventory;
using TaleWorlds.Core.ViewModelCollection.Information;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.Library;

namespace MyLittleWarbandEx.ViewModel
{
    public class EquipmentTooltipInnerContent : Inventory__TaleWorlds_CampaignSystem_ViewModelCollection_Inventory_SPInventoryVM_Dependency_24_InventoryTooltipInnerContent__DependendPrefab
    {

        public EquipmentTooltipInnerContent(UIContext context) : base(context)
        {
        }

    }
}
